// GERADO AUTOMATICAMENTE por scripts/gerar-champions.mjs — não edite à mão
export const escudosChampions = {
  "Club Brugge KV": "https://crests.football-data.org/851.png",
  "Aston Villa FC": "https://crests.football-data.org/58.png",
  "PAE AEK": "https://crests.football-data.org/1899.png",
  "LASK Linz": "https://crests.football-data.org/2016.png",
  "Real Madrid CF": "https://crests.football-data.org/86.png",
  "FC Internazionale Milano": "https://crests.football-data.org/108.png",
  "FC Porto": "https://crests.football-data.org/503.png",
  "Manchester City FC": "https://crests.football-data.org/65.png",
  "Borussia Dortmund": "https://crests.football-data.org/4.png",
  "Villarreal CF": "https://crests.football-data.org/94.png",
  "Lille OSC": "https://crests.football-data.org/521.png",
  "Real Betis Balompié": "https://crests.football-data.org/90.png",
  "FC Barcelona": "https://crests.football-data.org/81.png",
  "Feyenoord Rotterdam": "https://crests.football-data.org/675.png",
  "VfB Stuttgart": "https://crests.football-data.org/10.png",
  "Viking FK": "https://crests.football-data.org/5720.png",
  "Liverpool FC": "https://crests.football-data.org/64.png",
  "Club Atlético de Madrid": "https://crests.football-data.org/78.png",
  "Paris Saint-Germain FC": "https://crests.football-data.org/524.png",
  "ŠK Slovan Bratislava": "https://crests.football-data.org/7509.png",
  "SSC Napoli": "https://crests.football-data.org/113.png",
  "Arsenal FC": "https://crests.football-data.org/57.png",
  "Sporting Clube de Portugal": "https://crests.football-data.org/498.png",
  "Galatasaray SK": "https://crests.football-data.org/610.png",
  "Fenerbahçe SK": "https://crests.football-data.org/613.png",
  "AS Roma": "https://crests.football-data.org/100.png",
  "PSV": "https://crests.football-data.org/674.png",
  "FK Shakhtar Donetsk": "https://crests.football-data.org/1887.png",
  "FC Bayern München": "https://crests.football-data.org/5.png",
  "FK Bodø/Glimt": "https://crests.football-data.org/5721.png",
  "Manchester United FC": "https://crests.football-data.org/66.png",
  "Sabah FK": "https://crests.football-data.org/10233.png",
  "Como 1907": "https://crests.football-data.org/7397.png",
  "RB Leipzig": "https://crests.football-data.org/721.png",
  "SK Slavia Praha": "https://crests.football-data.org/930.png",
  "Racing Club de Lens": "https://crests.football-data.org/546.png"
};
